[package]

name="hello market"
version="0.1.3"
license="MIT"

[address]

hello_market="_" //address of the module that contains the marketplace
std="0x1" // standard library 
aptos_framework= "" // address
aptos_std= "0x1"
aptos_token= "0x3"

[dependencies]

AptosFramework = _ // github
AptosStdlib = _
AptosToken = _
